//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 03:57:00 PM IST 
//


package com.tripcase.api.partner;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeoAccuracy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GeoAccuracy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="point"/>
 *     &lt;enumeration value="address"/>
 *     &lt;enumeration value="intersection"/>
 *     &lt;enumeration value="range"/>
 *     &lt;enumeration value="block"/>
 *     &lt;enumeration value="admin1"/>
 *     &lt;enumeration value="postal4"/>
 *     &lt;enumeration value="admin2"/>
 *     &lt;enumeration value="postal2"/>
 *     &lt;enumeration value="city"/>
 *     &lt;enumeration value="county"/>
 *     &lt;enumeration value="state"/>
 *     &lt;enumeration value="admin3"/>
 *     &lt;enumeration value="country"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GeoAccuracy")
@XmlEnum
public enum GeoAccuracy {

    @XmlEnumValue("point")
    POINT("point"),
    @XmlEnumValue("address")
    ADDRESS("address"),
    @XmlEnumValue("intersection")
    INTERSECTION("intersection"),
    @XmlEnumValue("range")
    RANGE("range"),
    @XmlEnumValue("block")
    BLOCK("block"),
    @XmlEnumValue("admin1")
    ADMIN_1("admin1"),
    @XmlEnumValue("postal4")
    POSTAL_4("postal4"),
    @XmlEnumValue("admin2")
    ADMIN_2("admin2"),
    @XmlEnumValue("postal2")
    POSTAL_2("postal2"),
    @XmlEnumValue("city")
    CITY("city"),
    @XmlEnumValue("county")
    COUNTY("county"),
    @XmlEnumValue("state")
    STATE("state"),
    @XmlEnumValue("admin3")
    ADMIN_3("admin3"),
    @XmlEnumValue("country")
    COUNTRY("country");
    private final String value;

    GeoAccuracy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GeoAccuracy fromValue(String v) {
        for (GeoAccuracy c: GeoAccuracy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
