//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 03:57:00 PM IST 
//


package com.tripcase.api.partner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeoCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeoCode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tripcase.com/api/partner}LatLng">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="Accuracy" type="{http://tripcase.com/api/partner}GeoAccuracy" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeoCode")
public class GeoCode
    extends LatLng
{

    @XmlAttribute(name = "Accuracy")
    protected GeoAccuracy accuracy;

    /**
     * Gets the value of the accuracy property.
     * 
     * @return
     *     possible object is
     *     {@link GeoAccuracy }
     *     
     */
    public GeoAccuracy getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoAccuracy }
     *     
     */
    public void setAccuracy(GeoAccuracy value) {
        this.accuracy = value;
    }

}
