//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 03:57:00 PM IST 
//


package com.tripcase.api.partner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImportItineraryRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportItineraryRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PartnerCredentials" type="{http://tripcase.com/api/partner}PartnerCredentials"/>
 *         &lt;element name="Itinerary" type="{http://tripcase.com/api/partner}Itinerary"/>
 *         &lt;element name="PartnerProperties" type="{http://tripcase.com/api/partner}Properties" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="UserEmail" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SuppressImportEmails" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportItineraryRequest", propOrder = {
    "partnerCredentials",
    "itinerary",
    "partnerProperties"
})
public class ImportItineraryRequest {

    @XmlElement(name = "PartnerCredentials", required = true)
    protected PartnerCredentials partnerCredentials;
    @XmlElement(name = "Itinerary", required = true)
    protected Itinerary itinerary;
    @XmlElement(name = "PartnerProperties")
    protected Properties partnerProperties;
    @XmlAttribute(name = "UserEmail", required = true)
    protected String userEmail;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "SuppressImportEmails")
    protected Boolean suppressImportEmails;

    /**
     * Gets the value of the partnerCredentials property.
     * 
     * @return
     *     possible object is
     *     {@link PartnerCredentials }
     *     
     */
    public PartnerCredentials getPartnerCredentials() {
        return partnerCredentials;
    }

    /**
     * Sets the value of the partnerCredentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnerCredentials }
     *     
     */
    public void setPartnerCredentials(PartnerCredentials value) {
        this.partnerCredentials = value;
    }

    /**
     * Gets the value of the itinerary property.
     * 
     * @return
     *     possible object is
     *     {@link Itinerary }
     *     
     */
    public Itinerary getItinerary() {
        return itinerary;
    }

    /**
     * Sets the value of the itinerary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Itinerary }
     *     
     */
    public void setItinerary(Itinerary value) {
        this.itinerary = value;
    }

    /**
     * Gets the value of the partnerProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getPartnerProperties() {
        return partnerProperties;
    }

    /**
     * Sets the value of the partnerProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setPartnerProperties(Properties value) {
        this.partnerProperties = value;
    }

    /**
     * Gets the value of the userEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * Sets the value of the userEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserEmail(String value) {
        this.userEmail = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the suppressImportEmails property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuppressImportEmails() {
        return suppressImportEmails;
    }

    /**
     * Sets the value of the suppressImportEmails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuppressImportEmails(Boolean value) {
        this.suppressImportEmails = value;
    }

}
