//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 03:57:00 PM IST 
//


package com.tripcase.api.partner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Location complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Location">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{http://tripcase.com/api/partner}Address" minOccurs="0"/>
 *         &lt;element name="LocationReference" type="{http://tripcase.com/api/partner}LocationReference" minOccurs="0"/>
 *         &lt;element name="GeoCode" type="{http://tripcase.com/api/partner}GeoCode" minOccurs="0"/>
 *         &lt;element name="ClosestAirport" type="{http://tripcase.com/api/partner}AirportCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Location", propOrder = {
    "address",
    "locationReference",
    "geoCode",
    "closestAirport"
})
public class Location {

    @XmlElement(name = "Address")
    protected Address address;
    @XmlElement(name = "LocationReference")
    protected LocationReference locationReference;
    @XmlElement(name = "GeoCode")
    protected GeoCode geoCode;
    @XmlElement(name = "ClosestAirport")
    protected AirportCode closestAirport;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the locationReference property.
     * 
     * @return
     *     possible object is
     *     {@link LocationReference }
     *     
     */
    public LocationReference getLocationReference() {
        return locationReference;
    }

    /**
     * Sets the value of the locationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationReference }
     *     
     */
    public void setLocationReference(LocationReference value) {
        this.locationReference = value;
    }

    /**
     * Gets the value of the geoCode property.
     * 
     * @return
     *     possible object is
     *     {@link GeoCode }
     *     
     */
    public GeoCode getGeoCode() {
        return geoCode;
    }

    /**
     * Sets the value of the geoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoCode }
     *     
     */
    public void setGeoCode(GeoCode value) {
        this.geoCode = value;
    }

    /**
     * Gets the value of the closestAirport property.
     * 
     * @return
     *     possible object is
     *     {@link AirportCode }
     *     
     */
    public AirportCode getClosestAirport() {
        return closestAirport;
    }

    /**
     * Sets the value of the closestAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportCode }
     *     
     */
    public void setClosestAirport(AirportCode value) {
        this.closestAirport = value;
    }

}
