//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 03:57:00 PM IST 
//


package com.tripcase.api.partner;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tripcase.api.partner package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImportItineraryRequest_QNAME = new QName("http://tripcase.com/api/partner", "ImportItineraryRequest");
    private final static QName _ImportItineraryResponse_QNAME = new QName("http://tripcase.com/api/partner", "ImportItineraryResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tripcase.api.partner
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link PartnerCredentials }
     * 
     */
    public PartnerCredentials createPartnerCredentials() {
        return new PartnerCredentials();
    }

    /**
     * Create an instance of {@link Air }
     * 
     */
    public Air createAir() {
        return new Air();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link GeoCode }
     * 
     */
    public GeoCode createGeoCode() {
        return new GeoCode();
    }

    /**
     * Create an instance of {@link LocationReference }
     * 
     */
    public LocationReference createLocationReference() {
        return new LocationReference();
    }

    /**
     * Create an instance of {@link ItineraryReference }
     * 
     */
    public ItineraryReference createItineraryReference() {
        return new ItineraryReference();
    }

    /**
     * Create an instance of {@link Itinerary }
     * 
     */
    public Itinerary createItinerary() {
        return new Itinerary();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link ImportItineraryResponse }
     * 
     */
    public ImportItineraryResponse createImportItineraryResponse() {
        return new ImportItineraryResponse();
    }

    /**
     * Create an instance of {@link LatLng }
     * 
     */
    public LatLng createLatLng() {
        return new LatLng();
    }

    /**
     * Create an instance of {@link TourStop }
     * 
     */
    public TourStop createTourStop() {
        return new TourStop();
    }

    /**
     * Create an instance of {@link TourEvent }
     * 
     */
    public TourEvent createTourEvent() {
        return new TourEvent();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Seat }
     * 
     */
    public Seat createSeat() {
        return new Seat();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link LocationEvent }
     * 
     */
    public LocationEvent createLocationEvent() {
        return new LocationEvent();
    }

    /**
     * Create an instance of {@link ImportItineraryRequest }
     * 
     */
    public ImportItineraryRequest createImportItineraryRequest() {
        return new ImportItineraryRequest();
    }

    /**
     * Create an instance of {@link Seats }
     * 
     */
    public Seats createSeats() {
        return new Seats();
    }

    /**
     * Create an instance of {@link AirportCode }
     * 
     */
    public AirportCode createAirportCode() {
        return new AirportCode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportItineraryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tripcase.com/api/partner", name = "ImportItineraryRequest")
    public JAXBElement<ImportItineraryRequest> createImportItineraryRequest(ImportItineraryRequest value) {
        return new JAXBElement<ImportItineraryRequest>(_ImportItineraryRequest_QNAME, ImportItineraryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportItineraryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tripcase.com/api/partner", name = "ImportItineraryResponse")
    public JAXBElement<ImportItineraryResponse> createImportItineraryResponse(ImportItineraryResponse value) {
        return new JAXBElement<ImportItineraryResponse>(_ImportItineraryResponse_QNAME, ImportItineraryResponse.class, null, value);
    }

}
