//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.19 at 03:57:00 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tripcase.com/api/partner", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tripcase.api.partner;
