//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.21 at 12:01:28 PM IST 
//


package com.worldmate.schemas.worldmate_api_v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for items complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="items">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="flight" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}flight"/>
 *         &lt;element name="car-rental" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}car-rental"/>
 *         &lt;element name="hotel-reservation" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}hotel-reservation"/>
 *         &lt;element name="public-transportation" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}public-transportation"/>
 *         &lt;element name="event" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}event"/>
 *         &lt;element name="meeting" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}meeting"/>
 *       &lt;/choice>
 *       &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "items", propOrder = {
    "flightOrCarRentalOrHotelReservation"
})
public class Items {

    @XmlElements({
        @XmlElement(name = "public-transportation", type = PublicTransportation.class),
        @XmlElement(name = "car-rental", type = CarRental.class),
        @XmlElement(name = "flight", type = Flight.class),
        @XmlElement(name = "meeting", type = Meeting.class),
        @XmlElement(name = "hotel-reservation", type = HotelReservation.class),
        @XmlElement(name = "event", type = Event.class)
    })
    protected List<ItineraryItem> flightOrCarRentalOrHotelReservation;
    @XmlAttribute(name = "size", required = true)
    protected int size;

    /**
     * Gets the value of the flightOrCarRentalOrHotelReservation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightOrCarRentalOrHotelReservation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightOrCarRentalOrHotelReservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicTransportation }
     * {@link CarRental }
     * {@link Flight }
     * {@link Meeting }
     * {@link HotelReservation }
     * {@link Event }
     * 
     * 
     */
    public List<ItineraryItem> getFlightOrCarRentalOrHotelReservation() {
        if (flightOrCarRentalOrHotelReservation == null) {
            flightOrCarRentalOrHotelReservation = new ArrayList<ItineraryItem>();
        }
        return this.flightOrCarRentalOrHotelReservation;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public int getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     */
    public void setSize(int value) {
        this.size = value;
    }

}
