//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.21 at 12:01:28 PM IST 
//


package com.worldmate.schemas.worldmate_api_v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.worldmate.schemas.worldmate_api_v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.worldmate.schemas.worldmate_api_v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EndUserEmails }
     * 
     */
    public EndUserEmails createEndUserEmails() {
        return new EndUserEmails();
    }

    /**
     * Create an instance of {@link ProviderDetails }
     * 
     */
    public ProviderDetails createProviderDetails() {
        return new ProviderDetails();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link CarRental }
     * 
     */
    public CarRental createCarRental() {
        return new CarRental();
    }

    /**
     * Create an instance of {@link Meeting }
     * 
     */
    public Meeting createMeeting() {
        return new Meeting();
    }

    /**
     * Create an instance of {@link PriceDetails }
     * 
     */
    public PriceDetails createPriceDetails() {
        return new PriceDetails();
    }

    /**
     * Create an instance of {@link LoyaltyProgram }
     * 
     */
    public LoyaltyProgram createLoyaltyProgram() {
        return new LoyaltyProgram();
    }

    /**
     * Create an instance of {@link GeoLocation }
     * 
     */
    public GeoLocation createGeoLocation() {
        return new GeoLocation();
    }

    /**
     * Create an instance of {@link PublicTransportation }
     * 
     */
    public PublicTransportation createPublicTransportation() {
        return new PublicTransportation();
    }

    /**
     * Create an instance of {@link Headers }
     * 
     */
    public Headers createHeaders() {
        return new Headers();
    }

    /**
     * Create an instance of {@link Traveler }
     * 
     */
    public Traveler createTraveler() {
        return new Traveler();
    }

    /**
     * Create an instance of {@link BookingDetails }
     * 
     */
    public BookingDetails createBookingDetails() {
        return new BookingDetails();
    }

    /**
     * Create an instance of {@link HotelReservation }
     * 
     */
    public HotelReservation createHotelReservation() {
        return new HotelReservation();
    }

    /**
     * Create an instance of {@link CarRentalLocaion }
     * 
     */
    public CarRentalLocaion createCarRentalLocaion() {
        return new CarRentalLocaion();
    }

    /**
     * Create an instance of {@link EndUserEmail }
     * 
     */
    public EndUserEmail createEndUserEmail() {
        return new EndUserEmail();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AirportDetails }
     * 
     */
    public AirportDetails createAirportDetails() {
        return new AirportDetails();
    }

    /**
     * Create an instance of {@link CodedName }
     * 
     */
    public CodedName createCodedName() {
        return new CodedName();
    }

    /**
     * Create an instance of {@link PublicTransportationLocaion }
     * 
     */
    public PublicTransportationLocaion createPublicTransportationLocaion() {
        return new PublicTransportationLocaion();
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link FlightDetails }
     * 
     */
    public FlightDetails createFlightDetails() {
        return new FlightDetails();
    }

    /**
     * Create an instance of {@link WorldmateParsingResult }
     * 
     */
    public WorldmateParsingResult createWorldmateParsingResult() {
        return new WorldmateParsingResult();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetails();
    }

    /**
     * Create an instance of {@link Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

}
