//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.21 at 12:01:28 PM IST 
//


package com.worldmate.schemas.worldmate_api_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reservation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reservation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}itinerary-item">
 *       &lt;sequence>
 *         &lt;element name="record-locator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="booking-details" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}booking-details" minOccurs="0"/>
 *         &lt;element name="provider-details" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}provider-details" minOccurs="0"/>
 *         &lt;element name="total-price" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}price-details" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservation", propOrder = {
    "recordLocator",
    "bookingDetails",
    "providerDetails",
    "totalPrice"
})
@XmlSeeAlso({
    Flight.class,
    PublicTransportation.class,
    Event.class,
    CarRental.class,
    HotelReservation.class
})
public class Reservation
    extends ItineraryItem
{

    @XmlElement(name = "record-locator")
    protected String recordLocator;
    @XmlElement(name = "booking-details")
    protected BookingDetails bookingDetails;
    @XmlElement(name = "provider-details")
    protected ProviderDetails providerDetails;
    @XmlElement(name = "total-price")
    protected PriceDetails totalPrice;

    /**
     * Gets the value of the recordLocator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordLocator() {
        return recordLocator;
    }

    /**
     * Sets the value of the recordLocator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordLocator(String value) {
        this.recordLocator = value;
    }

    /**
     * Gets the value of the bookingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BookingDetails }
     *     
     */
    public BookingDetails getBookingDetails() {
        return bookingDetails;
    }

    /**
     * Sets the value of the bookingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingDetails }
     *     
     */
    public void setBookingDetails(BookingDetails value) {
        this.bookingDetails = value;
    }

    /**
     * Gets the value of the providerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderDetails }
     *     
     */
    public ProviderDetails getProviderDetails() {
        return providerDetails;
    }

    /**
     * Sets the value of the providerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderDetails }
     *     
     */
    public void setProviderDetails(ProviderDetails value) {
        this.providerDetails = value;
    }

    /**
     * Gets the value of the totalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PriceDetails }
     *     
     */
    public PriceDetails getTotalPrice() {
        return totalPrice;
    }

    /**
     * Sets the value of the totalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceDetails }
     *     
     */
    public void setTotalPrice(PriceDetails value) {
        this.totalPrice = value;
    }

}
