//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.21 at 12:01:28 PM IST 
//


package com.worldmate.schemas.worldmate_api_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error-msg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="headers" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}headers"/>
 *         &lt;element name="end-user-emails" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}end-user-emails"/>
 *         &lt;element name="reservation-details" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}reservation" minOccurs="0"/>
 *         &lt;element name="items" type="{http://www.worldmate.com/schemas/worldmate-api-v1.xsd}items" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="received" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="request-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "errorMsg",
    "headers",
    "endUserEmails",
    "reservationDetails",
    "items"
})
@XmlRootElement(name = "worldmate-parsing-result")
public class WorldmateParsingResult {

    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "error-msg")
    protected String errorMsg;
    @XmlElement(required = true)
    protected Headers headers;
    @XmlElement(name = "end-user-emails", required = true)
    protected EndUserEmails endUserEmails;
    @XmlElement(name = "reservation-details")
    protected Reservation reservationDetails;
    protected Items items;
    @XmlAttribute(name = "received", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar received;
    @XmlAttribute(name = "request-id", required = true)
    protected String requestId;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the errorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * Sets the value of the errorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMsg(String value) {
        this.errorMsg = value;
    }

    /**
     * Gets the value of the headers property.
     * 
     * @return
     *     possible object is
     *     {@link Headers }
     *     
     */
    public Headers getHeaders() {
        return headers;
    }

    /**
     * Sets the value of the headers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Headers }
     *     
     */
    public void setHeaders(Headers value) {
        this.headers = value;
    }

    /**
     * Gets the value of the endUserEmails property.
     * 
     * @return
     *     possible object is
     *     {@link EndUserEmails }
     *     
     */
    public EndUserEmails getEndUserEmails() {
        return endUserEmails;
    }

    /**
     * Sets the value of the endUserEmails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndUserEmails }
     *     
     */
    public void setEndUserEmails(EndUserEmails value) {
        this.endUserEmails = value;
    }

    /**
     * Gets the value of the reservationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Reservation }
     *     
     */
    public Reservation getReservationDetails() {
        return reservationDetails;
    }

    /**
     * Sets the value of the reservationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reservation }
     *     
     */
    public void setReservationDetails(Reservation value) {
        this.reservationDetails = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link Items }
     *     
     */
    public Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link Items }
     *     
     */
    public void setItems(Items value) {
        this.items = value;
    }

    /**
     * Gets the value of the received property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceived() {
        return received;
    }

    /**
     * Sets the value of the received property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceived(XMLGregorianCalendar value) {
        this.received = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

}
